package com.esko.Model;
// Generated May 23, 2017 2:40:19 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Attendancefeed generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "attendancefeed", catalog = "spandana")
public class Attendancefeed implements java.io.Serializable {

	private AttendancefeedId id;
	private Employeedetails employeedetails;
	private Date checkIn;
	private Date checkOut;
	private String dayDuration;
	private String status;

	public Attendancefeed() {
	}

	public Attendancefeed(AttendancefeedId id, Employeedetails employeedetails, Date checkIn, Date checkOut,
			String dayDuration,String status) {
		this.id = id;
		this.employeedetails = employeedetails;
		this.checkIn = checkIn;
		this.checkOut = checkOut;
		this.dayDuration = dayDuration;
		this.status = status;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "employeeIdAf", column = @Column(name = "employeeIdAF", nullable = false, length = 30)),
			@AttributeOverride(name = "attendanceDate", column = @Column(name = "attendanceDate", nullable = false, length = 10)) })
	public AttendancefeedId getId() {
		return this.id;
	}

	public void setId(AttendancefeedId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "employeeIdAF", nullable = false, insertable = false, updatable = false)
	public Employeedetails getEmployeedetails() {
		return this.employeedetails;
	}

	public void setEmployeedetails(Employeedetails employeedetails) {
		this.employeedetails = employeedetails;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "checkIn", nullable = false, length = 8)
	public Date getCheckIn() {
		return this.checkIn;
	}

	public void setCheckIn(Date checkIn) {
		this.checkIn = checkIn;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "checkOut", nullable = false, length = 8)
	public Date getCheckOut() {
		return this.checkOut;
	}

	public void setCheckOut(Date checkOut) {
		this.checkOut = checkOut;
	}

	@Column(name = "dayDuration", nullable = false, length = 45)
	public String getDayDuration() {
		return this.dayDuration;
	}
	
	public void setDayDuration(String dayDuration) {
		this.dayDuration = dayDuration;
	}

	@Column(name = "status", nullable = false, length = 45)
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	
}
