package com.esko.Model;
// Generated May 20, 2017 3:36:40 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttendancefeedId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class AttendancefeedId implements java.io.Serializable {

	private String employeeIdAf;
	private Date attendanceDate;

	public AttendancefeedId() {
	}

	public AttendancefeedId(String employeeIdAf, Date attendanceDate) {
		this.employeeIdAf = employeeIdAf;
		this.attendanceDate = attendanceDate;
	}

	@Column(name = "employeeIdAF", nullable = false, length = 30)
	public String getEmployeeIdAf() {
		return this.employeeIdAf;
	}

	public void setEmployeeIdAf(String employeeIdAf) {
		this.employeeIdAf = employeeIdAf;
	}

	@Column(name = "attendanceDate", nullable = false, length = 10)
	public Date getAttendanceDate() {
		return this.attendanceDate;
	}

	public void setAttendanceDate(Date attendanceDate) {
		this.attendanceDate = attendanceDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AttendancefeedId))
			return false;
		AttendancefeedId castOther = (AttendancefeedId) other;

		return ((this.getEmployeeIdAf() == castOther.getEmployeeIdAf()) || (this.getEmployeeIdAf() != null
				&& castOther.getEmployeeIdAf() != null && this.getEmployeeIdAf().equals(castOther.getEmployeeIdAf())))
				&& ((this.getAttendanceDate() == castOther.getAttendanceDate())
						|| (this.getAttendanceDate() != null && castOther.getAttendanceDate() != null
								&& this.getAttendanceDate().equals(castOther.getAttendanceDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmployeeIdAf() == null ? 0 : this.getEmployeeIdAf().hashCode());
		result = 37 * result + (getAttendanceDate() == null ? 0 : this.getAttendanceDate().hashCode());
		return result;
	}

}
