package com.esko.Model;
// Generated Jun 20, 2017 4:45:50 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Employeerole generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "employeerole", catalog = "spandana")
public class Employeerole implements java.io.Serializable {

	private Integer id;
	private Employeedetails employeedetails;
	private Rolemaster rolemaster;

	public Employeerole() {
	}

	public Employeerole(Employeedetails employeedetails, Rolemaster rolemaster) {
		this.employeedetails = employeedetails;
		this.rolemaster = rolemaster;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employeeIdER", nullable = false)
	public Employeedetails getEmployeedetails() {
		return this.employeedetails;
	}

	public void setEmployeedetails(Employeedetails employeedetails) {
		this.employeedetails = employeedetails;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "roleIdER", nullable = false)
	public Rolemaster getRolemaster() {
		return this.rolemaster;
	}

	public void setRolemaster(Rolemaster rolemaster) {
		this.rolemaster = rolemaster;
	}

}
