package com.esko.Model;
// Generated May 19, 2017 12:28:57 PM by Hibernate Tools 5.1.0.Alpha1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Employeemanagerdetails generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "employeemanagerdetails", catalog = "spandana")
public class Employeemanagerdetails implements java.io.Serializable {

	private int id;
	@JsonManagedReference
	private Employeedetails employeedetailsByManagerIdEm;
	@JsonManagedReference
	private Employeedetails employeedetailsByEmployeeIdEm;

	public Employeemanagerdetails() {
	}

	public Employeemanagerdetails(Employeedetails employeedetailsByManagerIdEm,
			Employeedetails employeedetailsByEmployeeIdEm) {
		this.employeedetailsByManagerIdEm = employeedetailsByManagerIdEm;
		this.employeedetailsByEmployeeIdEm = employeedetailsByEmployeeIdEm;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "managerIdEM", nullable = false)
	public Employeedetails getEmployeedetailsByManagerIdEm() {
		return this.employeedetailsByManagerIdEm;
	}

	public void setEmployeedetailsByManagerIdEm(Employeedetails employeedetailsByManagerIdEm) {
		this.employeedetailsByManagerIdEm = employeedetailsByManagerIdEm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employeeIdEM", nullable = false)
	public Employeedetails getEmployeedetailsByEmployeeIdEm() {
		return this.employeedetailsByEmployeeIdEm;
	}

	public void setEmployeedetailsByEmployeeIdEm(Employeedetails employeedetailsByEmployeeIdEm) {
		this.employeedetailsByEmployeeIdEm = employeedetailsByEmployeeIdEm;
	}

}
