package com.esko.Model;
// Generated Jul 7, 2017 12:47:02 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LeavefeedId generated by hbm2java
 */
@SuppressWarnings("serial")
@Embeddable
public class LeavefeedId implements java.io.Serializable {

	private String employeeIdLf;
	private Date leaveDate;
	private String duration;

	public LeavefeedId() {
	}

	public LeavefeedId(String employeeIdLf, Date leaveDate, String duration) {
		this.employeeIdLf = employeeIdLf;
		this.leaveDate = leaveDate;
		this.duration = duration;
	}

	@Column(name = "employeeIdLF", nullable = false, length = 30)
	public String getEmployeeIdLf() {
		return this.employeeIdLf;
	}

	public void setEmployeeIdLf(String employeeIdLf) {
		this.employeeIdLf = employeeIdLf;
	}

	@Column(name = "leaveDate", nullable = false, length = 10)
	public Date getLeaveDate() {
		return this.leaveDate;
	}

	public void setLeaveDate(Date leaveDate) {
		this.leaveDate = leaveDate;
	}

	@Column(name = "duration", nullable = false, length = 45)
	public String getDuration() {
		return this.duration;
	}

	public void setDuration(String duration) {
		this.duration = duration;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LeavefeedId))
			return false;
		LeavefeedId castOther = (LeavefeedId) other;

		return ((this.getEmployeeIdLf() == castOther.getEmployeeIdLf()) || (this.getEmployeeIdLf() != null
				&& castOther.getEmployeeIdLf() != null && this.getEmployeeIdLf().equals(castOther.getEmployeeIdLf())))
				&& ((this.getLeaveDate() == castOther.getLeaveDate()) || (this.getLeaveDate() != null
						&& castOther.getLeaveDate() != null && this.getLeaveDate().equals(castOther.getLeaveDate())))
				&& ((this.getDuration() == castOther.getDuration()) || (this.getDuration() != null
						&& castOther.getDuration() != null && this.getDuration().equals(castOther.getDuration())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getEmployeeIdLf() == null ? 0 : this.getEmployeeIdLf().hashCode());
		result = 37 * result + (getLeaveDate() == null ? 0 : this.getLeaveDate().hashCode());
		result = 37 * result + (getDuration() == null ? 0 : this.getDuration().hashCode());
		return result;
	}

}
