package com.esko.Model;
// Generated Jun 20, 2017 4:45:50 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Rolemaster generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "rolemaster", catalog = "spandana", uniqueConstraints = @UniqueConstraint(columnNames = "roleName"))
public class Rolemaster implements java.io.Serializable {

	private Integer roleId;
	private String roleName;
	@JsonBackReference
	private Set<Employeerole> employeeroles = new HashSet<Employeerole>(0);

	public Rolemaster() {
	}

	public Rolemaster(String roleName) {
		this.roleName = roleName;
	}

	public Rolemaster(String roleName, Set<Employeerole> employeeroles) {
		this.roleName = roleName;
		this.employeeroles = employeeroles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "roleId", unique = true, nullable = false)
	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	@Column(name = "roleName", unique = true, nullable = false)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rolemaster")
	public Set<Employeerole> getEmployeeroles() {
		return this.employeeroles;
	}

	public void setEmployeeroles(Set<Employeerole> employeeroles) {
		this.employeeroles = employeeroles;
	}

}
